2022-08-17 10:06:28,975 INFO    MainThread:388332 [wandb_setup.py:_flush():76] Configure stats pid to 388332
2022-08-17 10:06:28,975 INFO    MainThread:388332 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2022-08-17 10:06:28,975 INFO    MainThread:388332 [wandb_setup.py:_flush():76] Loading settings from /home/compu/jh/project/colon_compare/scripts/logs/evaluations/runs/ubc/voting/2022-08-17_10-05-39/wandb/settings
2022-08-17 10:06:28,975 INFO    MainThread:388332 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True'}
2022-08-17 10:06:28,975 WARNING MainThread:388332 [wandb_setup.py:_flush():76] Could not find program at ../test.py
2022-08-17 10:06:28,975 INFO    MainThread:388332 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../test.py'}
2022-08-17 10:06:28,975 INFO    MainThread:388332 [wandb_init.py:_log_setup():461] Logging user logs to ./wandb/run-20220817_100628-22yeshza/logs/debug.log
2022-08-17 10:06:28,976 INFO    MainThread:388332 [wandb_init.py:_log_setup():462] Logging internal logs to ./wandb/run-20220817_100628-22yeshza/logs/debug-internal.log
2022-08-17 10:06:28,976 INFO    MainThread:388332 [wandb_init.py:init():495] calling init triggers
2022-08-17 10:06:28,976 INFO    MainThread:388332 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-08-17 10:06:28,976 INFO    MainThread:388332 [wandb_init.py:init():548] starting backend
2022-08-17 10:06:28,976 INFO    MainThread:388332 [wandb_init.py:init():552] setting up manager
2022-08-17 10:06:28,981 INFO    MainThread:388332 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-17 10:06:28,983 INFO    MainThread:388332 [wandb_init.py:init():558] backend started and connected
2022-08-17 10:06:28,994 INFO    MainThread:388332 [wandb_init.py:init():636] updated telemetry
2022-08-17 10:06:29,171 INFO    MainThread:388332 [wandb_init.py:init():667] communicating run to backend with 30 second timeout
2022-08-17 10:06:59,172 INFO    MainThread:388332 [interface_shared.py:_communicate_run():331] couldn't get run from backend
2022-08-17 10:06:59,172 ERROR   MainThread:388332 [wandb_init.py:init():676] backend process timed out
2022-08-17 10:06:59,172 ERROR   MainThread:388332 [wandb_init.py:init():685] encountered error: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-08-17 10:07:38,156 WARNING MsgRouterThr:388332 [router.py:message_loop():76] message_loop has been closed
