2022-08-17 09:59:09,981 INFO    MainThread:377172 [wandb_setup.py:_flush():76] Configure stats pid to 377172
2022-08-17 09:59:09,981 INFO    MainThread:377172 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2022-08-17 09:59:09,981 INFO    MainThread:377172 [wandb_setup.py:_flush():76] Loading settings from /home/compu/jh/project/colon_compare/scripts/logs/evaluations/runs/ubc/voting/2022-08-17_09-58-25/wandb/settings
2022-08-17 09:59:09,981 INFO    MainThread:377172 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True'}
2022-08-17 09:59:09,981 WARNING MainThread:377172 [wandb_setup.py:_flush():76] Could not find program at ../test.py
2022-08-17 09:59:09,981 INFO    MainThread:377172 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../test.py'}
2022-08-17 09:59:09,982 INFO    MainThread:377172 [wandb_init.py:_log_setup():461] Logging user logs to ./wandb/run-20220817_095909-2283grbb/logs/debug.log
2022-08-17 09:59:09,982 INFO    MainThread:377172 [wandb_init.py:_log_setup():462] Logging internal logs to ./wandb/run-20220817_095909-2283grbb/logs/debug-internal.log
2022-08-17 09:59:09,982 INFO    MainThread:377172 [wandb_init.py:init():495] calling init triggers
2022-08-17 09:59:09,982 INFO    MainThread:377172 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-08-17 09:59:09,982 INFO    MainThread:377172 [wandb_init.py:init():548] starting backend
2022-08-17 09:59:09,982 INFO    MainThread:377172 [wandb_init.py:init():552] setting up manager
2022-08-17 09:59:09,984 INFO    MainThread:377172 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-17 09:59:09,987 INFO    MainThread:377172 [wandb_init.py:init():558] backend started and connected
2022-08-17 09:59:10,004 INFO    MainThread:377172 [wandb_init.py:init():636] updated telemetry
2022-08-17 09:59:10,151 INFO    MainThread:377172 [wandb_init.py:init():667] communicating run to backend with 30 second timeout
2022-08-17 09:59:40,152 INFO    MainThread:377172 [interface_shared.py:_communicate_run():331] couldn't get run from backend
2022-08-17 09:59:40,152 ERROR   MainThread:377172 [wandb_init.py:init():676] backend process timed out
2022-08-17 09:59:40,152 ERROR   MainThread:377172 [wandb_init.py:init():685] encountered error: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-08-17 10:00:12,018 WARNING MsgRouterThr:377172 [router.py:message_loop():76] message_loop has been closed
